### ISSUE TITLE
sliding window documentation

### ISSUE THREAD

**Issue by ngn** [JohnEarnest/ok#76]
"sliding window" is [documented](https://github.com/JohnEarnest/ok/blob/gh-pages/docs/Fromk5Tok6.md#window-done) as `'` and marked "done", but it only works as `':`

**Comment by JohnEarnest** [comment]
You're correct; the meaning shifted without updating that document. Since the official k6 is completely dead and/or tied up in copyright hell while in an unfinished state, I no longer see perfect compatibility terribly important. The oK manual is up to date.

In 67e80dc2a33acf5d3626fff081a29b68cc2bb705 I have added a disclaimer to those transitional notes to prevent confusion.
