### ISSUE TITLE
Humble enhancement suggestions for the oK Mobile app

### ISSUE THREAD

**Issue by tommythorn** [JohnEarnest/ok#91]
First off, this is a brilliant idea, thanks for sharing.

I used the J iOS App (no longer available/working) and it wasn't as useful as a calculator because the iOS keyboard is not ideal.  However, using it I immediately missed some of the things that makes Free42 so great: haptic feedback and space between keys (which makes mistyping less likely).

Also, I'm not actually skilled enough in Apl/J/K so a one-button access to a quick overview of the keys would make this a nice learning tool.

**Comment by JohnEarnest** [comment]
Haptic feedback is tricky in a webapp; as far as I'm aware, there's no portable API for it. I'm really not interested in rewriting this as a native application, since it would cost _me_ money to get an iOS developer license even if I distributed it for free, and I'd have to jump through extra hoops to support other platforms and fight bit-rot.

I'm open to concrete ideas for increasing space between keys, but it's a tough series of tradeoffs. The current layout works for me on my 4" iPhone SE, which is rather small compared to most phones today. If you happen to be using an iPad or the like, you might have better results simply using oK's [normal web repl](http://johnearnest.github.io/ok/index.html). oK mobile will also try to switch between "QWERTY mode" and "calculator mode" keyboards based on the orientation of your device; perhaps the horizontal version is more pleasant for you to type on?

Having access to a reference card seems like a reasonable enhancement.

**Comment by tommythorn** [comment]
... apparently Apple's Safari doesn't implement the vibration support :(  according to https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate, sigh

EDIT: apparently we raced :)  Didn't see your update until replying.

**Comment by JohnEarnest** [comment]
Yeah, it's a bummer. :(
